config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :users, only: [:new, :create]

  resources :ads, only: [:new, :create, :edit, :update]

  # login
  resources :sessions, only: [:new, :create] do
    collection do
      delete "sign_out", to: "sessions#destroy", as: "sign_out"
    end
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /[^\s]@[^\s]/
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: EMAIL_FORMAT }, uniqueness: true

  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :require_logged_user

  def new
    @ad = Ad.new
  end

  def edit
    @ad = current_user.ads.find(params[:id])
  end

  def create
    @ad = current_user.ads.build(ad_params)
    if @ad.save
      redirect_to root_path, notice: "Anúncio criado com sucesso"
    end
  end

  def update
    @ad = current_user.ads.find(params[:id])
    if @ad.update(ad_params)
      redirect_to edit_ad_path(@ad), notice: "Anúncio atualizado com sucesso"
    else
      render :edit
    end
  end

  private

  def ad_params
    params.require(:ad).permit(:title, :description, :prince)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :user_signed_in?, :current_user

  def user_signed_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_logged_user
    redirect_to new_session_path, alert: "Você precisa estar logado para entrar nessa tela" unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @ads = Ad.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      reset_session
      session[:user_id] = user.id
      redirect_to root_path, notice: t(".welcome", name: user.name)
    else
      redirect_to new_session_path, alert: t(".invalid_credentials")
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path, notice: t(".session_finished")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      NotificationMailer.welcome(@user.name, @user.email).deliver_later
      redirect_to new_session_path, notice: t(".success")
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for ad do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :prince %>
    <%= form.number_field :prince %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editar anúncio</h1>

<%= render "form", ad: @ad %>

app/views/ads/new.html.erb
<h1>Novo anúncio</h1>

<%= render "form", ad: @ad %>

app/views/home/show.html.erb
<h1>Anúncios</h1>


<div>
  <ul>
    <% @ads.each do |ad| %>
      <li>
        <p><%= link_to "Editar", edit_ad_path(ad) %></p>
        <p><strong><%= ad.title %></strong></p>
        <p><%= ad.description %></p>
        <p><%= ad.prince %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classificados</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p>
    <%= flash.notice %>
    <%= flash.alert %>
  </p>

    <nav>
      <% if user_signed_in? %>
        <%= button_to t("menu.logout"), sign_out_sessions_path, method: :delete %>
        <%= link_to t("menu.new_ad"), new_ad_path %>
      <% else %>
        <%= link_to t("menu.signup"), new_user_path %>
        <%= link_to t("menu.signin"), new_session_path %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1><%= t("title.signup") %></h1>

<% if @user.errors.any? %>
  <p><%= t("title.error") %></p>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, url: "/users" do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>